import type { ProjectConfig } from '@/types/config'
import type { ComposeDSL } from '@/types/dsl'
import { deps, devDeps, scripts, when } from '@/utils/file-helper'
import { isFrontendProject, isReactProject, isVueProject } from '@/utils/type-guard'

function basePackageJson(config: ProjectConfig) {
  return {
    name: config.name,
    type: 'module',
    version: '0.0.0',
    description: `A ${config.type} project generated by create-yume`,
    license: 'MIT',
    engines: {
      node: '>=18.12.0',
    },
    scripts: {},
    dependencies: {},
    devDependencies: {},
  }
}

export function buildPackageJson(dsl: ComposeDSL, config: ProjectConfig) {
  const entry = dsl.json('package.json')
    .base(() => basePackageJson(config))
    .modify(when(config.language === 'typescript', devDeps({ typescript: '^5.9.2' })))
    // 暂时锁一段时间版本，等 issue 解掉
    .modify(when(config.linting === 'antfu-eslint', devDeps({ '@antfu/eslint-config': '5.2.2', 'eslint': '^9.34.0' })))
    .modify(when(config.linting === 'antfu-eslint', scripts({ 'lint': 'eslint', 'lint:fix': 'eslint --fix' })))
    .modify(when(config.git, devDeps({ '@lobehub/commit-cli': '^2.19.0' })))
    .modify(when(config.git, scripts({ 'commit': 'lobe-commit --hook', 'commit:config': 'lobe-commit --option' })))
    .modify(when(config.codeQuality.length > 0, devDeps({ husky: '^9.1.7' })))
    .modify(when(config.codeQuality.includes('lint-staged'), devDeps({ 'lint-staged': '^16.1.6' })))
    .modify(when(config.codeQuality.includes('commitlint'), devDeps({ '@commitlint/cli': '^19.8.1', '@commitlint/config-conventional': '^19.8.1' })))

  if (isFrontendProject(config)) {
    entry
      .modify(when(config.buildTool === 'vite', deps({ vite: '^7.1.3' })))
      .modify(when(config.buildTool === 'vite', scripts({ dev: 'vite', build: 'vite build', preview: 'vite preview' })))

      .modify(when(config.cssPreprocessor === 'sass', devDeps({ sass: '^1.91.0' })))
      .modify(when(config.cssPreprocessor === 'less', devDeps({ less: '^4.4.1' })))

      .modify(when(config.cssFramework === 'tailwind', deps({ 'tailwindcss': '^4.1.12', '@tailwindcss/vite': '^4.1.12' })))

    if (isVueProject(config)) {
      entry
        .modify(when(config.language === 'typescript', devDeps({ '@vue/tsconfig': '^0.8.1' })))
        .modify(when(config.buildTool === 'vite', deps({ '@vitejs/plugin-vue': '^6.0.1', '@vue/compiler-sfc': '^3.5.20' })))
        .modify(deps({ vue: '^3.5.20' }))
        .modify(when(config.router, deps({ 'vue-router': '^4.5.1' })))
        .modify(when(config.stateManagement, deps({ pinia: '^3.0.3' })))
    }
    else if (isReactProject(config)) {
      entry
        .modify(deps({ 'react': '^19.1.1', 'react-dom': '^19.1.1' }))
        .modify(when(config.buildTool === 'vite', deps({ '@vitejs/plugin-react': '^5.0.2' })))
        .modify(when(config.linting === 'antfu-eslint', devDeps({ '@eslint-react/eslint-plugin': '^1.53.0', 'eslint-plugin-react-hooks': '^5.2.0', 'eslint-plugin-react-refresh': '^0.4.20' })))
        .modify(when(config.router === 'react-router', deps({ 'react-router': '^7.8.2', 'react-router-dom': '^7.8.2' })))
        .modify(when(config.router === 'tanstack-router', deps({ '@tanstack/react-router': '^1.131.35' })))
        .modify(when(config.language === 'typescript', devDeps({ '@types/react': '^19.1.12', '@types/react-dom': '^19.1.9' })))
        .modify(when(config.stateManagement === 'zustand', deps({ zustand: '^5.0.8' })))
        .modify(when(config.stateManagement === 'jotai', deps({ jotai: '^2.13.1' })))
    }

    entry.sortKeys(true)
  }
}
