import type { ProjectConfig } from '@/types/config'
import type { ComposeDSL } from '@/types/dsl'
import { makePackageName } from '@/brand/package-name'
import { deps, devDeps, scripts, when } from '@/utils/file-helper'
import { isFrontendProject, isReactProject, isVueProject } from '@/utils/type-guard'

function basePackageJson(config: ProjectConfig) {
  return {
    name: makePackageName(config.name),
    type: 'module',
    version: '0.0.0',
    description: `A ${config.type} project generated by create-yume`,
    license: 'MIT',
    engines: {
      node: '>=18.12.0',
    },
    scripts: {},
    dependencies: {},
    devDependencies: {},
  }
}

export function buildPackageJson(dsl: ComposeDSL, config: ProjectConfig) {
  const entry = dsl.json('package.json')
    .base(() => basePackageJson(config))
    .modify(when(config.language === 'typescript', devDeps({ typescript: '^6.0.3' })))
    .modify(when(config.linting === 'antfu-eslint', devDeps({ '@antfu/eslint-config': '^8.2.0', 'eslint': '^10.2.1' })))
    .modify(when(config.linting === 'antfu-eslint', scripts({ 'lint': 'eslint', 'lint:fix': 'eslint --fix' })))
    .modify(when(config.git, devDeps({ '@lobehub/commit-cli': '^2.19.0' })))
    .modify(when(config.git, scripts({ 'commit': 'lobe-commit --hook', 'commit:config': 'lobe-commit --option' })))
    .modify(when(config.codeQuality.length > 0, devDeps({ husky: '^9.1.7' })))
    .modify(when(config.codeQuality.includes('lint-staged'), devDeps({ 'lint-staged': '^16.4.0' })))
    .modify(when(config.codeQuality.includes('commitlint'), devDeps({ '@commitlint/cli': '^20.5.0', '@commitlint/config-conventional': '^20.5.0' })))

  if (isFrontendProject(config)) {
    entry
      .modify(when(config.buildTool === 'vite', deps({ vite: '^8.0.9' })))
      .modify(when(config.buildTool === 'vite', scripts({ dev: 'vite', build: 'vite build', preview: 'vite preview' })))

      .modify(when(config.cssPreprocessor === 'sass', devDeps({ sass: '^1.99.0' })))
      .modify(when(config.cssPreprocessor === 'less', devDeps({ less: '^4.6.4' })))

      .modify(when(config.cssFramework === 'tailwind', deps({ 'tailwindcss': '^4.2.4', '@tailwindcss/vite': '^4.2.4' })))

    if (isVueProject(config)) {
      entry
        .modify(when(config.language === 'typescript', devDeps({ '@vue/tsconfig': '^0.9.1' })))
        .modify(when(config.buildTool === 'vite', deps({ '@vitejs/plugin-vue': '^6.0.6', '@vue/compiler-sfc': '^3.5.32' })))
        .modify(deps({ vue: '^3.5.32' }))
        .modify(when(config.router, deps({ 'vue-router': '^5.0.4' })))
        .modify(when(config.stateManagement, deps({ pinia: '^3.0.4' })))
    }
    else if (isReactProject(config)) {
      entry
        .modify(deps({ 'react': '^19.2.5', 'react-dom': '^19.2.5' }))
        .modify(when(config.buildTool === 'vite', deps({ '@vitejs/plugin-react': '^6.0.1' })))
        .modify(when(config.linting === 'antfu-eslint', devDeps({ '@eslint-react/eslint-plugin': '^4.2.3', 'eslint-plugin-react-hooks': '^7.1.1', 'eslint-plugin-react-refresh': '^0.5.2' })))
        .modify(when(config.router === 'react-router', deps({ 'react-router': '^7.14.2', 'react-router-dom': '^7.14.2' })))
        .modify(when(config.router === 'tanstack-router', deps({ '@tanstack/react-router': '^1.168.23' })))
        .modify(when(config.language === 'typescript', devDeps({ '@types/react': '^19.2.14', '@types/react-dom': '^19.2.3' })))
        .modify(when(config.stateManagement === 'zustand', deps({ zustand: '^5.0.12' })))
        .modify(when(config.stateManagement === 'jotai', deps({ jotai: '^2.19.1' })))
    }

    entry.sortKeys(true)
  }
}
